version: '3'
services:
  postgres:
    container_name: postgres-holyjs-demo
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432
  prisma:
    container_name: prisma-holyjs-demo
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-holyjs-demo
            user: postgres
            password: postgres
            port: 5432
            database: postgres